/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Staker } from "./Staker";
export type { TokenA } from "./TokenA";
export type { TokenB } from "./TokenB";
